[tool.poetry]
name        = "DepthFlow"
version     = "2024.2.6"
description = "Image to 2.5D Parallax Effect Video"
authors     = ["Tremeschin <tremeschin@users.noreply.github.com>"]
license     = "AGPLv3-only"

[[tool.poetry.packages]]
include = "DepthFlow"

[tool.poetry.scripts]
main = "DepthFlow.__main__:main"

[tool.poe.tasks]
_install_venv       = "poetry install"
_install_torch_cuda = "python -m pip install torch==2.0.1 torchvision"
_install_torch_rocm = "python -m pip install torch==2.0.1 torchvision --index-url https://download.pytorch.org/whl/rocm5.7"
_install_torch_cpu  = "python -m pip install torch==2.0.1 torchvision --index-url https://download.pytorch.org/whl/cpu"
_uninstall_torch    = "python -m pip uninstall -y torch torchvision"
cuda                = ["_install_venv", "_uninstall_torch", "_install_torch_cuda"]
rocm                = ["_install_venv", "_uninstall_torch", "_install_torch_rocm"]
cpu                 = ["_install_venv", "_uninstall_torch", "_install_torch_cpu" ]

[build-system]
requires      = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python        = ">=3.10,<3.13"
timm          = "0.6.7"
gradio        = "^4.13.0"
broken-source = "^2024.1.15"
transformers  = "^4.37.1"
torch         = {version="2.0.1", source="torch-cpu"}
torchvision   = "0.15.2"

[tool.poetry.dev-dependencies]
broken-source = {path="../../", develop=true}
shaderflow    = {path="../ShaderFlow", develop=true}

[[tool.poetry.source]]
name     = "torch-cpu"
priority = "explicit"
url      = "https://download.pytorch.org/whl/cpu"

[[tool.poetry.source]]
name     = "torch-cuda"
priority = "explicit"
url      = "https://download.pytorch.org/whl/cu118"

[[tool.poetry.source]]
name     = "torch-rocm"
priority = "explicit"
url      = "https://download.pytorch.org/whl/rocm5.4.2"
