[project]
name         = "depthflow"
version      = "2024.3.27"
description  = "Image to 2.5D Parallax Effect Video"
authors      = [{name="Tremeschin", email="29046864+Tremeschin@users.noreply.github.com"}]
readme       = "Readme.md"
dependencies = [
    "broken-source>=2024.1.15",
]
requires-python = ">=3.10"

[project.scripts]
depthflow = "DepthFlow.__main__:main"

[tool.rye]
managed = true

# # Hatchling

[tool.hatch.build.targets.wheel]
packages = ["DepthFlow"]

[build-system]
requires      = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true
